# Generated by Django 3.2.6 on 2021-08-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_camera', '0006_alter_camera_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='img/thumbnail'),
        ),
    ]
