# Generated by Django 3.2.6 on 2021-08-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='camera_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
