# Generated by Django 3.2.4 on 2021-09-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip_camera', '0007_alter_camera_thumbnail'),
        ('main', '0003_auto_20210907_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupy', models.BooleanField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_camera.camera')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='camera_data',
            field=models.ManyToManyField(to='main.Camera_Data'),
        ),
    ]
