# Generated by Django 3.2.4 on 2021-09-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_camera_data_occupy'),
        ('main', '0006_auto_20210908_1450'),
    ]

    operations = [
    ]
