# Generated by Django 3.2.4 on 2021-09-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_camera', '0007_alter_camera_thumbnail'),
        ('main', '0002_seat_camera_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='camera_number',
        ),
        migrations.AddField(
            model_name='seat',
            name='camera_name',
            field=models.ManyToManyField(to='ip_camera.Camera'),
        ),
    ]
