# Generated by Django 3.2.6 on 2021-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_camera_name_seat_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera_data',
            name='occupy',
            field=models.IntegerField(),
        ),
    ]
