# Generated by Django 3.2.4 on 2021-09-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20210911_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occupy_History',
            new_name='OccupyHistory',
        ),
    ]
