# Generated by Django 3.2.4 on 2021-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_camera', '0004_alter_camera_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='img/thumbnail'),
        ),
    ]
